/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.io.File;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Pratik
 */
public class ClientSetup extends javax.swing.JFrame {

    /**
     * Creates new form ClientSetup
     */
    ClientDemo client ;
    
    public ClientSetup() {
        initComponents();
        
        client=new ClientDemo(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmain = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        txtmsg = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        lblname = new javax.swing.JLabel();
        clientlist = new java.awt.List();
        jLabel4 = new javax.swing.JLabel();
        btnsendfile = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtfile = new javax.swing.JTextField();
        btnfilechoose = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Client");

        txtmain.setColumns(20);
        txtmain.setRows(5);
        jScrollPane1.setViewportView(txtmain);

        jLabel2.setText("Message");

        jButton1.setText("Send");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        clientlist.setMultipleMode(true);

        jLabel4.setText("Clients List");

        btnsendfile.setText("SendFile");
        btnsendfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendfileActionPerformed(evt);
            }
        });

        jLabel3.setText("Select File");

        txtfile.setEditable(false);

        btnfilechoose.setText("Choose");
        btnfilechoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfilechooseActionPerformed(evt);
            }
        });

        jLabel5.setText("Client Name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtfile, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnfilechoose, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnsendfile, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clientlist, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE))
                        .addContainerGap(34, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(118, 118, 118))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblname, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clientlist, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtmsg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnfilechoose)
                    .addComponent(btnsendfile))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
         System.out.println(""+clientlist.isMultipleMode());
        txtmain.append("Client Says : "+txtmsg.getText());
        System.out.println(""+clientlist.getSelectedIndexes().length);
        if(clientlist.getSelectedIndexes().length==0)
        {
        client.sendMessage(txtmsg.getText());
        
       // System.out.println("hello1");
        
        }
       else 
         {   
             int count=clientlist.getSelectedIndexes().length;
             System.out.println("Count Value Is : "+count);
             if(count>1)
              {
           System.out.println("Hello3");
         String arr[]= clientlist.getSelectedItems();
             //  ArrayList lst=new ArrayList();
             ArrayList lst=new ArrayList();
             
             for(String i:arr)
             {
                 lst.add(i);
                 
                 
             }
             
             //client.sendToManyClient(txtmsg.getText(),lst);
             
             
         }
             else
             {
             
             System.out.println("Hello2");
         String sip=clientlist.getSelectedItem();
         System.out.println(sip);
         client.sendMessageToClient(txtmsg.getText(),sip);
        // System.out.println(""+clientlist.getItemCount());
         }
         }
       
      
       
        }catch(Exception ee)
        {
            System.out.println("Hello "+ee);
        }
        
        
        
        
        /* if(clientlist.getItemCount()>1) */
      
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnsendfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendfileActionPerformed

        try{
            System.out.println(clientlist.getSelectedIndexes().length+"");
            if(clientlist.getSelectedIndexes().length==0)
            {
             
                if(txtfile.getText().length()==0)
                {
                    JOptionPane.showMessageDialog(null,"Please Choose A File");
                    return;
                }
                else
                {    
                    String path=txtfile.getText();
                  //  client.confirmation(path);\
                    System.out.println(path);
                    client.sendFileToServer(path);
               
                }
                
                
            }
            else{
                 String sip=clientlist.getSelectedItem();
                
                String path=txtfile.getText();
                client.sendFileToClient(path,sip);
            }
            
            
        }catch(Exception ee)
        {
            System.out.println("Exception : "+ee);
        }
        
        
    }//GEN-LAST:event_btnsendfileActionPerformed

    private void btnfilechooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfilechooseActionPerformed

        JFileChooser chooser=new JFileChooser();
        
       int value= chooser.showOpenDialog(this);
        if(value==JFileChooser.APPROVE_OPTION)
        {
            File f= chooser.getSelectedFile();
            
            String path= f.getPath();
            
            txtfile.setText(path);
            
        }
        
    }//GEN-LAST:event_btnfilechooseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientSetup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientSetup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnfilechoose;
    private javax.swing.JButton btnsendfile;
    public java.awt.List clientlist;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblname;
    private javax.swing.JTextField txtfile;
    public javax.swing.JTextArea txtmain;
    private javax.swing.JTextField txtmsg;
    // End of variables declaration//GEN-END:variables
}
